language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO='django>=1.8.0,<1.9.0'
  - DJANGO='django>=1.9.0,<1.10.0'
  - DJANGO='django>=1.10.0'
  - DJANGO='django>=1.11.0'
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
install:
  - pip install selenium
  - pip install requests
  - pip install -r requirements.txt
  - pip install $DJANGO
script:
  - python runtests.py
notifications:
  email: false
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.2"
      env: DJANGO='django>=1.9.0,<1.10.0'
    - python: "3.3"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.3"
      env: DJANGO='django>=1.9.0,<1.10.0'
    - python: "3.4"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.5"
      env: DJANGO='django>=1.7.0,<1.8.0'
    - python: "3.6"
      env: DJANGO='django>=1.8.0,<1.9.0'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
